all:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c

1:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_1.txt

2:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_15.txt

3:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_20.txt

4:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_40.txt

5:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_50.txt

6:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_80.txt

7:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_100.txt

8:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_150.txt

9:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/testFile_200.txt

clean:
	rm dataStructure

