all:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c

1:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test1.txt

2:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test2.txt

3:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test3.txt

4:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test4.txt

5:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test5.txt

6:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test6.txt

7:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test7.txt

8:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test8.txt

9:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test8.txt

10:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test10.txt

11:
	clear
	gcc -Wall -o dataStructure main/*.c functions/*c
	./dataStructure testfiles/test11.txt

clean:
	rm dataStructure

